version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      # - ~/apps/postgres:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=jared
      - POSTGRES_DB=postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"

  # zookeeper:
  #   image: arm64v8/zookeeper:latest
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - '2181:2181'
  #     - '2888:2888'
  #     - '3888:3888'
  #
  # kafka:
  #   image: wurstmeister/kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - '9092:9092'
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: INSIDE://
  #
  #
  # connect:
  #   image: debezium/connect:2.5
  #   ports:
  #     - '8083:8083'
  #   environment:
  #     - BOOTSTRAP_SERVERS=kafka:9092
  #     - GROUP_ID=1
  #     - CONFIG_STORAGE_TOPIC=my_connect_configs
  #     - OFFSET_STORAGE_TOPIC=my_connect_offsets
  #     - STATUS_STORAGE_TOPIC=my_connect_statuses
  #     - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
  #     - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
  #     - CONNECT_KEY_COVERTER_SCHEMAS_REGISTRY_URL=http://schema-registry:8081
  #     - CONNECT_VALUE_COVERTER_SCHEMAS_REGISTRY_URL=http://schema-registry:8081
  #   links:
  #     - kafka
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:6.2.0
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
  #     SCHMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081,http://localhost:8081
  #   depends_on:
  #     - kafka
  #     - zookeeper
  #
  # kafka_manager:
  #   image: hlebalbau/kafka-manager:stable
  #   ports:
  #     - '9000:9000'
  #   environment:
  #     ZK_HOSTS: zookeeper:2181
  #     APPLICATION_SECRET: letmein
  #   command:
  #     - "-Dpidfile.path=/dev/null"
  #   depends_on:
  #     - zookeeper
  #     - kafka
